name: 🐞 Bug Report
description: Reportar um bug ou comportamento inesperado
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug!  
        Por favor, preencha as informações abaixo com o máximo de detalhes possível.

  - type: input
    id: summary
    attributes:
      label: Resumo do Bug
      description: Explique em uma frase o problema observado.
      placeholder: O que aconteceu de errado?

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos para reproduzir o problema.
      placeholder: |
        1. Vá até '...'
        2. Clique em '...'
        3. Observe o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      placeholder: O que você esperava que acontecesse?

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informe detalhes do sistema, versão, etc.
      placeholder: |
        - Sistema operacional:
        - Versão do app:
        - Navegador:

  - type: textarea
    id: extra
    attributes:
      label: Informações adicionais
      placeholder: Logs, prints, ou insights extras