name: 🧩 Template de Tasks
description: Criação de uma nova tarefa (feature, correção, documentação, etc.)
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Título da issue:** comece com um **verbo no infinitivo** (ex.: *Criar*, *Ajustar*, *Finalizar*).
        Exemplo: **Criar endpoint de login no azure**

  - type: input
    id: solicitante
    attributes:
      label: Solicitante
      description: Quem está pedindo essa tarefa?
      placeholder: Nome do solicitante
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva a tarefa a ser realizada.
      placeholder: Detalhe o que é entregável na tarefa, o objetivo, etc.
    validations:
      required: true
