name: 🐞 Bug Report
description: Reportar um bug ou comportamento inesperado
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug!  
        Por favor, preencha as informações abaixo com o máximo de detalhes possível.

  - type: input
    id: summary
    attributes:
      label: Resumo do Bug
      description: Explique em uma frase o problema observado.
      placeholder: O que aconteceu de errado?

  - type: input
    id: deadline
    attributes:
      label: 📅 Prazo estimado
      description: Informe a data prevista para resolução (formato DD-MM-AAAA).
      placeholder: 30-10-2025
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Área responsável
      description: Selecione a área relacionada ao bug.
      options:
        - Engenharia
        - BI
    validations:
      required: true
