name: 🧩 Template de Tasks
description: Criação de uma nova tarefa (feature, correção, documentação, etc.)
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Título da issue:** comece com um **verbo no infinitivo** (ex.: *Criar*, *Ajustar*, *Finalizar*).
        Exemplo: **Criar endpoint de login**

  - type: input
    id: prazo
    attributes:
      label: Prazo estimado
      description: Informe a data prevista (formato DD/MM/AA).
      placeholder: 30/10/25
    validations:
      required: false

  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade
      description: Defina a urgência da tarefa.
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: true

  - type: input
    id: solicitante
    attributes:
      label: Solicitante
      description: Quem está pedindo essa tarefa?
      placeholder: Nome do solicitante
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Área
      description: Escolha a área responsável.
      options:
        - ENG
        - BI
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva a tarefa a ser realizada.
      placeholder: Detalhe o que é entregável na tarefa, o objetivo, etc.
    validations:
      required: true
