name: Job Application
description: Track a job application process
title: "<Application Description> @ <Company Name>"
projects: ["💼 application tracker"]
assignees:
  - taniomi
body:
  - type: checkboxes
    attributes:
      label: Application Steps
      options:
        - label: 📧 Email sent
        - label: 📥 Application submitted
        - label: 🔗 LinkedIn connection made
        - label: 📩 In contact with company
        - label: 🧑💼 Interview scheduled/completed
        - label: 🤝 Deal closed
        - label: 🔮 Future opportunities
  - type: dropdown
    id: position
    attributes:
      label: Position
      options:
        - Junior Data Engineer
        - Data Engineer
        - Senior Data Engineer
        - Data Engineer Intern
        
        - Junior Data Analytics
        - Data Analytics
        - Senior Data Analytics

        - Junior Data Analyst
        - Data Analyst
    validations:
      required: true
  - type: input
    id: job_posting
    attributes:
      label: Link to Job Posting
      placeholder: Enter URL
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: Add any additional details
    validations:
      required: false