name: Set current iteration (Projects v2)

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number para testar manualmente"
        required: false
        type: string

jobs:
  set-iteration:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read
    env:
      GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}             # PAT classic: project, read:org (+ repo se privado)
      PROJECT_ID: PVT_kwDODkGqB84BGE05                    # seu Project v2
      FIELD_ID:   PVTIF_lADODkGqB84BGE05zg3XHl0           # campo Iteration

    steps:
      - name: Sanity / whoami
        shell: bash
        run: |
          gh --version
          echo "GH_TOKEN length: ${#GH_TOKEN}"
          gh api user

      - name: Resolver ISSUE_NODE_ID (evento ou manual)
        id: issue
        shell: bash
        run: |
          if [ -n "${{ inputs.issue_number }}" ]; then
            NUM="${{ inputs.issue_number }}"
          else
            NUM="${{ github.event.issue.number }}"
          fi
          if [ -z "$NUM" ]; then
            echo "Nenhum issue_number disponível." >&2
            exit 1
          fi
          echo "ISSUE_NUMBER=$NUM" >> $GITHUB_ENV
          NODE_ID=$(gh api repos/${{ github.repository }}/issues/$NUM -q .node_id)
          if [ -z "$NODE_ID" ]; then
            echo "Não consegui obter node_id da issue #$NUM em ${{ github.repository }}." >&2
            exit 1
          fi
          echo "ISSUE_NODE_ID=$NODE_ID" >> $GITHUB_ENV
          echo "node_id=$NODE_ID"

      - name: Adicionar item ao Project (idempotente)
        id: additem
        shell: bash
        run: |
          # 1) adicionar a issue ao Project (idempotente)
          MUT='mutation($project:ID!, $content:ID!){
            addProjectV2ItemById(input:{projectId:$project, contentId:$content}) {
              item { id }
            }
          }'
          gh api graphql -f query="$MUT" -f project="$PROJECT_ID" -f content="$ISSUE_NODE_ID" > add.json || true
          echo "add.json:"; cat add.json || true

          # 2) tentar extrair o ITEM_ID direto do retorno
          python3 - <<'PY' > item.env
          import json, sys
          try:
              data = json.load(open('add.json','r',encoding='utf-8'))
              iid = data['data']['addProjectV2ItemById']['item']['id']
              if iid:
                  print(f"ITEM_ID={iid}")
          except Exception as e:
              pass
          PY

          # 3) se não veio, fazer fallback com retry (até 5 tentativas)
          source item.env 2>/dev/null || true
          if [ -z "${ITEM_ID:-}" ]; then
            echo "ITEM_ID não veio no retorno; tentando localizar via query (com retry)..."
            Q='query($project:ID!, $issue:String!) {
              node(id:$project) {
                ... on ProjectV2 {
                  items(first:100, query:$issue) { nodes { id } }
                }
              }
            }'
            for i in 1 2 3 4 5; do
              ITEM_ID=$(gh api graphql -f query="$Q" -f project="$PROJECT_ID" -f issue="$ISSUE_NODE_ID" -q .data.node.items.nodes[0].id 2>/dev/null || true)
              if [ -n "$ITEM_ID" ]; then
                break
              fi
              echo "retry $i..."
              sleep 2
            done
          fi

          if [ -z "${ITEM_ID:-}" ]; then
            echo "Item não encontrado no Project após adicionar e retries." >&2
            exit 1
          fi

          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV
          echo "item_id=$ITEM_ID"


      - name: Obter config do campo Iteration
        id: getfield
        shell: bash
        run: |
          Q='query($project:ID!){
            node(id:$project){
              ... on ProjectV2 {
                fields(first:50){
                  nodes{
                    __typename
                    ... on ProjectV2IterationField {
                      id name
                      configuration { iterations { id title startDate duration } }
                    }
                  }
                }
              }
            }
          }'
          gh api graphql -f query="$Q" -f project="$PROJECT_ID" > project_fields.json
          echo "TODAY=$(TZ=America/Sao_Paulo date +%F)" >> $GITHUB_ENV
          echo "today=$(TZ=America/Sao_Paulo date +%F)"

      - name: Calcular iterationId atual (São Paulo)
        id: pickiter
        shell: bash
        run: |
          python3 - <<'PY' | tee iter.env
          import json, os, sys
          from datetime import date, timedelta

          today_str = os.environ.get("TODAY")
          if not today_str:
              print("Sem TODAY no env", file=sys.stderr)
              sys.exit(1)
          today = date.fromisoformat(today_str)

          data = json.load(open("project_fields.json","r", encoding="utf-8"))
          fields = data["data"]["node"]["fields"]["nodes"]
          FIELD_ID = os.environ["FIELD_ID"]

          iter_field = next((f for f in fields
                             if f.get("__typename")=="ProjectV2IterationField" and f.get("id")==FIELD_ID), None)
          if not iter_field:
              print("Campo Iteration não encontrado.", file=sys.stderr)
              sys.exit(1)

          iterations = (iter_field.get("configuration") or {}).get("iterations") or []
          current = None
          for it in iterations:
              sd, dur = it.get("startDate"), it.get("duration")
              if not sd or not dur:
                  continue
              start = date.fromisoformat(sd)
              end = start + timedelta(days=int(dur))
              if start <= today < end:
                  current = it["id"]
                  break

          if not current:
              print("Nenhuma iteração atual encontrada.", file=sys.stderr)
              sys.exit(1)

          print(f"ITERATION_ID={current}")
          PY
          source iter.env
          echo "ITERATION_ID=$ITERATION_ID" >> $GITHUB_ENV

      - name: Aplicar Iteration = current
        shell: bash
        run: |
          MUT='mutation($project:ID!, $item:ID!, $field:ID!, $iter:String!){
            updateProjectV2ItemFieldValue(
              input:{projectId:$project, itemId:$item, fieldId:$field, value:{iterationId:$iter}}
            ){ clientMutationId }
          }'
          gh api graphql -f query="$MUT" \
            -f project="$PROJECT_ID" \
            -f item="$ITEM_ID" \
            -f field="$FIELD_ID" \
            -f iter="$ITERATION_ID"
          echo "✅ Iteration aplicada."